const ADD_TEAM = "ADD_TEAM";
const DELETE_TEAM = "DELETE_TEAM";
const ADD_GAME = "ADD_GAME";
const FETCH_GAMES_BEGIN = "FETCH_GAMES_BEGIN";
const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
const FETCH_GAMES_FAILURE = "FETCH_GAMES_FAILURE";

export {
    ADD_TEAM,
    DELETE_TEAM,
    FETCH_GAMES_BEGIN,
    FETCH_GAMES_SUCCESS,
    FETCH_GAMES_FAILURE
}